# Polarization of Light --> Malus Law

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Exercise 1: Two Polarizers
Export data, analyze dependencies: Intensity vs. cos θ, and Intensity vs. cos<sup>2</sup>θ

### Organize data

In [68]:
# import data
ex1_01 = pd.read_csv("./Exercise1/Ex1_01.txt", sep='\t', header=1, skiprows=0)
ex1_02 = pd.read_csv("./Exercise1/Ex1_02.txt", sep='\t', header=1, skiprows=0)
ex1_03 = pd.read_csv("./Exercise1/Ex1_03.txt", sep='\t', header=1, skiprows=0)

display(ex1_01.head())
display(ex1_02.tail())

ex1 = [ex1_01, ex1_02, ex1_03]
display(ex1[2].tail())

   Sensor Position (Radians)  Light Intensity (Volts)
0                        0.0                  4.46213
1                        0.0                  4.46068
2                        0.0                  4.46262
3                        0.0                  4.46020
4                        0.0                  4.45778

     Sensor Position (Radians)  Light Intensity (Volts)
269                    3.12850                  4.37611
270                    3.12850                  4.36870
271                    3.12850                  4.37837
272                    3.13287                  4.35968
273                    3.15032                  4.34647

     Sensor Position (Radians)  Light Intensity (Volts)
219                    3.05869                  4.27914
220                    3.08487                  4.24144
221                    3.10669                  4.20923
222                    3.12850                  4.18007
223                    3.14596                  4.15381

In [69]:
# combine them
ex1_all = pd.concat(ex1, ignore_index=True)
ex1_all.info()
display(ex1_all.tail())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 818 entries, 0 to 817
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Sensor Position (Radians)  818 non-null    float64
 1   Light Intensity (Volts)    818 non-null    float64
dtypes: float64(2)
memory usage: 12.9 KB

     Sensor Position (Radians)  Light Intensity (Volts)
813                    3.05869                  4.27914
814                    3.08487                  4.24144
815                    3.10669                  4.20923
816                    3.12850                  4.18007
817                    3.14596                  4.15381

In [74]:
# order by intensity
ex1_all = ex1_all.sort_values(by=["Light Intensity (Volts)"], ascending=True)
ex1_all = ex1_all.reset_index(drop=True)
display(ex1_all)
#display(ex1_all.iloc[10:30])
#display(ex1_all.tail())

     Sensor Position (Radians)  Light Intensity (Volts)
0                      1.54462                 -0.01342
1                      1.56207                 -0.01294
2                      1.33954                 -0.01245
3                      1.32645                 -0.01229
4                      1.52280                 -0.01229
..                         ...                      ...
813                    0.04363                  4.46987
814                    0.01309                  4.47663
815                    0.02182                  4.47905
816                    0.03491                  4.47921
817                    0.00436                  4.48517

[818 rows x 2 columns]

In [73]:
# combine and get mean
ex1_all_comb = ex1_all.groupby('Light Intensity (Volts)').mean().reset_index()
ex1_all_comb.info()

# get std separately
temp_db = ex1_all.groupby('Light Intensity (Volts)').std().reset_index()
temp_db = temp_db.rename(columns={"Sensor Position (Radians)": "SP std"})

# combine
ex1_all_comb = pd.concat([ex1_all_comb, temp_db["SP std"]], axis=1)
display(ex1_all_comb)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Light Intensity (Volts)    780 non-null    float64
 1   Sensor Position (Radians)  780 non-null    float64
dtypes: float64(2)
memory usage: 12.3 KB

     Light Intensity (Volts)  Sensor Position (Radians)   SP std
0                   -0.01342                   1.544620      NaN
1                   -0.01294                   1.562070      NaN
2                   -0.01245                   1.339540      NaN
3                   -0.01229                   1.424625  0.13884
4                   -0.01213                   1.356990      NaN
..                       ...                        ...      ...
775                  4.46987                   0.043630      NaN
776                  4.47663                   0.013090      NaN
777                  4.47905                   0.021820      NaN
778                  4.47921                   0.034910      NaN
779                  4.48517                   0.004360      NaN

[780 rows x 3 columns]

### Plot Intensity vs cos(θ)

In [ ]:
# make the data
x = np.array(ex1_all_comb['Light Intensity (Volts)'].to_list())
y = np.array((ex1_all_comb['Sensor Position (Radians)']).to_list()) # MAKE THIS COS(THETA)
# MAKE ERRORBARS

# plot
fig, ax = plt.subplots()
ax.scatter(x, y)
ax.set_xlabel("Light Intensity (V)", fontsize=20)
ax.set_ylabel("cos(Sensor Position (rad))", fontsize=20)
#ax.errorbar(x, y, xerr=x_err, yerr=y_err[i], fmt='none')

### Exercise 1 Testing

In [66]:
# test combining data at the same light intensity

test_db = ex1_all.iloc[10:30]
#display(test_db)

# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html
# do std first bc will override df with mean
# - prob smarter to just make a separate one for the actual thing though
test1_db = test_db.groupby('Light Intensity (Volts)').std().reset_index()
test1_db = test1_db.rename(columns={"Sensor Position (Radians)": "SP std"})
#display(test1_db)

test_db = test_db.groupby('Light Intensity (Volts)').mean().reset_index()
#display(test_db)

test_db = pd.concat([test_db, test1_db["SP std"]], axis=1)

display(test_db)

    Light Intensity (Volts)  Sensor Position (Radians)    SP std
0                  -0.00762                   1.309000       NaN
1                  -0.00746                   1.378810       NaN
2                  -0.00440                   1.575160       NaN
3                  -0.00327                   1.605700       NaN
4                  -0.00198                   1.287180       NaN
5                  -0.00166                   1.596980       NaN
6                  -0.00150                   1.596980       NaN
7                  -0.00118                   1.596980       NaN
8                   0.00059                   1.437715  0.225235
9                   0.00092                   1.596980       NaN
10                  0.00124                   1.496620  0.141930
11                  0.00156                   1.592610       NaN
12                  0.00172                   1.492260       NaN
13                  0.00559                   1.605700       NaN
14                  0.00623                   1.274090       NaN
15                  0.00671                   1.588250       NaN
16                  0.00816                   1.583890       NaN
17                  0.00913                   1.274090       NaN